# Generated by Django 5.2.6 on 2025-10-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryRole',
            fields=[
                ('ID_Role', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('RoleType', models.CharField(max_length=1, unique=True)),
            ],
        ),
    ]
