# Generated by Django 5.2.6 on 2025-10-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryrole',
            name='RoleType',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
