# Generated by Django 5.2.7 on 2026-03-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
