# Generated by Django 5.2.7 on 2025-10-30 01:01

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
