# Generated by Django 5.2.7 on 2025-10-30 01:06

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_enable_vector_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Face',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
