# Generated by Django 5.2.6 on 2025-10-04 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dictionaryrole_roletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEmotion',
            fields=[
                ('ID_Emotion', models.AutoField(primary_key=True, serialize=False)),
                ('Emotion', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryFaculty',
            fields=[
                ('ID_Faculty', models.AutoField(primary_key=True, serialize=False)),
                ('Faculty', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryProgram',
            fields=[
                ('ID_Program', models.AutoField(primary_key=True, serialize=False)),
                ('Program', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('ID_SurveyResult', models.AutoField(primary_key=True, serialize=False)),
                ('Result', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID_User', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('UserPassword', models.CharField(max_length=255)),
                ('DateOfBirth', models.DateField()),
                ('Face', models.CharField(max_length=255, null=True)),
                ('DataAuth', models.BooleanField(default=False)),
                ('Semester', models.IntegerField()),
                ('FK_Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dictionaryfaculty')),
                ('FK_HealthcareProfessional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('FK_Program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dictionaryprogram')),
                ('FK_Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dictionaryrole')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('ID_Survey', models.AutoField(primary_key=True, serialize=False)),
                ('SurveyuDate', models.DateTimeField(auto_now_add=True)),
                ('FK_SurveyResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.surveyresult')),
                ('FK_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('ID_Recognition', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('RecognitionResults', models.CharField(max_length=255)),
                ('dateOfRecognition', models.DateTimeField(auto_now_add=True)),
                ('FK_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionRegister',
            fields=[
                ('ID_EmotionRegister', models.AutoField(primary_key=True, serialize=False)),
                ('EmotionDate', models.DateTimeField(auto_now_add=True)),
                ('FK_Emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dictionaryemotion')),
                ('FK_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
