# Generated by Django 5.2.7 on 2025-11-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usermodel_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionmodel',
            name='RecognitionResults',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
