from .dictionary_emotion_model import DictionaryEmotion
from .dictionary_faculty_model import DictionaryFaculty
from .dictionary_program_model import DictionaryProgram
from .dictionary_role_model import DictionaryRole
from .emotion_register_model import EmotionRegister
from .recognition_model import Recognition
from .survey_model import Survey
from .survey_result_model import SurveyResult
from .user_model import User
