from .tables.dictionary_emotion_model import DictionaryEmotion
from .tables.dictionary_faculty_model import DictionaryFaculty
from .tables.dictionary_program_model import DictionaryProgram
from .tables.dictionary_role_model import DictionaryRole
from .tables.emotion_register_model import EmotionRegister
from .tables.recognition_model import Recognition
from .tables.survey_model import Survey
from .tables.survey_result_model import SurveyResult
from .tables.user_model import User
