services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
      build:
        context: ./postgres

      environment:
        POSTGRES_DB: auraDb
        POSTGRES_USER: auraUser
        POSTGRES_PASSWORD: naruto77
      
      volumes:
        - pgdata:/var/lib/postgresql/data
        - ./postgres/postgresql.conf:/var/lib/postgres/data/postgresql.conf
      
      command: postgres -c config_file=/var/lib/postgres/data/postgresql.conf
      
      ports:
        - "5432:5432"

volumes:
  pgdata: